### ISSUE TITLE
pdf file

### ISSUE THREAD

**Issue by hamidkhaki** [ixuea/android-downloader#12]
hi, i can't download pdf file with androiddownloader
but i can download mp4, jpeg ... without any problem

**Comment by hamidkhaki** [comment]
i can't download this file:
https://kokersoft.ir/public/contents/document/6/5c3c5a4e9545e.pdf

**Comment by zhoutianjin** [comment]
Android8+需要配置网络安全配置,如下:
<domain-config cleartextTrafficPermitted="false">
                
                <domain includeSubdomains="true">example.com</domain>
                <domain includeSubdomains="true">cdn.example2.com</domain>
        </domain-config>
        　
        <base-config cleartextTrafficPermitted="true" />
还有不明白请联系:124360@qq.com

**Comment by zhoutianjin** [comment]
`<base-config cleartextTrafficPermitted="true" />`

**Comment by zhoutianjin** [comment]
Android8+需要配置网络安全配置,如下:
`<domain-config cleartextTrafficPermitted="false">
                
                <domain includeSubdomains="true">example.com</domain>
                <domain includeSubdomains="true">cdn.example2.com</domain>
        </domain-config>
        　
        <base-config cleartextTrafficPermitted="true" />`

还有不明白请联系:124360@qq.com

**Comment by ixueadev** [comment]
Thank you very much for your feedback. The problem has been fixed. If there are still problems, feel free to feedback or submit pr.
