### ISSUE TITLE
Still downloading after progress is larger than file size 

### ISSUE THREAD

**Issue by djaman** [ixuea/android-downloader#25]
**Android Downloader version**:
**Android Version**:
**Issue details/Repro steps**:
Continues download after progress larger than file size 
**Use code**:
```
Please paste your code here
```

**Stack trace**:
```
Please paste stack trace here
```

**Screenshot(if any)**:
Please image url here

**Comment by ixueadev** [comment]
Thank you very much for your feedback. The problem has been fixed. If there are still problems, feel free to feedback or submit pr.
