### ISSUE TITLE
Hi man  you project was toocomplicated

### ISSUE THREAD

**Issue by DioBrandoLong** [ixuea/android-downloader#4]
我甚至不知道如何在列表下载中 传递FILE

**Android Downloader version**:
**Android Version**:
**Issue details/Repro steps**:

**Use code**:
```
Please paste your code here
```

**Stack trace**:
```
Please paste stack trace here
```

**Screenshot(if any)**:
Please image url here

**Comment by ixueadev** [comment]
Hello, I don't understand your question.

**Comment by ixueadev** [comment]
Simple to use, you can view the demo, download a file, use it in the list, Download Manager and other scenarios.
