### ISSUE TITLE
存在无限下载的情况

### ISSUE THREAD

**Issue by A0058471** [ixuea/android-downloader#5]
“129105573，76907434”，前面是我log打印的，第一个是progress，后面是size。progress大于size后还一直在下载。

**Comment by ixueadev** [comment]
It is true that there are some problems, but they are all small probability events, which need more time to fix. Welcome to submit PR.

**Comment by ixueadev** [comment]
Thank you very much for your feedback. The problem has been fixed. If there are still problems, feel free to feedback or submit pr.
